/* =============================================================================
   Textbooker - seed test users (u1, a1) with password TestPass123!

   Adds two ASP.NET Identity accounts:
     - u1 (regular user)
     - a1 (member of the "Admin" role)

   The password hash below is a valid ASP.NET Identity v3 (PBKDF2) hash for
   TestPass123! - the same value UserManager.CreateAsync would produce.

   The committed version of this script intentionally does NOT contain database
   or schema names. Values are set in the DECLARE block below (marked REMOVE
   BEFORE COMMIT).

   Idempotent: re-running only updates rows that already exist.

   ============================================================================= */

/* >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
   LOCAL VALUES — REMOVE THIS BLOCK BEFORE COMMIT!
   (plain T-SQL — works in SSMS without SQLCMD mode)
   <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< */
DECLARE @ExpectedDatabase sysname = N'';
DECLARE @TargetSchema sysname = N'';

SET NOCOUNT ON;
SET XACT_ABORT ON;

/* Dynamic USE — a static USE does not accept variables. */
DECLARE @UseSql nvarchar(max) = N'USE ' + QUOTENAME(@ExpectedDatabase) + N';';
EXEC sys.sp_executesql @UseSql;

IF DB_NAME() <> @ExpectedDatabase
    THROW 50000, 'Skrypt uruchomiono na niewłaściwej bazie danych.', 1;

/* ASP.NET Identity v3 hash for TestPass123! (generated by PasswordHasher<T>). */
DECLARE @PasswordHash nvarchar(max) =
    N'AQAAAAIAAYagAAAAEDFNIgB1Qidc28josfzOIzTSlyz3Mum5fohYzEzIQrN9aoFRbHNWI8fMpw8iz5oz4w==';

DECLARE @SchemaPrefix nvarchar(300) = QUOTENAME(@TargetSchema) + N'.';

BEGIN TRANSACTION;

/* ---------------------------------------------------------------------------
   1. "Admin" role (id 1) - mirrors StartupUtilities.InitializeRolesAsync.
   --------------------------------------------------------------------------- */
DECLARE @RoleTable nvarchar(300) = @SchemaPrefix + N'[AspNetRoles]';

IF NOT EXISTS (SELECT 1 FROM sys.tables t WHERE t.object_id = OBJECT_ID(@RoleTable, N'U'))
    THROW 50010, N'Tabela AspNetRoles nie istnieje - uruchom najpierw migracje EF Core.', 1;

DECLARE @InsertRole nvarchar(max) = N'
IF NOT EXISTS (SELECT 1 FROM ' + @RoleTable + N' WHERE [NormalizedName] = N''ADMIN'')
    INSERT INTO ' + @RoleTable + N' ([Name], [NormalizedName], [ConcurrencyStamp])
    VALUES (N''Admin'', N''ADMIN'', LOWER(CONVERT(nvarchar(36), NEWID())));';
EXEC sys.sp_executesql @InsertRole;

DECLARE @AdminRoleId int;

/* Read the role id through dynamic SQL (schema is a variable). */
DECLARE @GetRoleId nvarchar(max) = N'SELECT @RoleIdOut = [Id] FROM ' + @RoleTable + N' WHERE [NormalizedName] = N''ADMIN'';';
EXEC sys.sp_executesql @GetRoleId, N'@RoleIdOut int OUTPUT', @RoleIdOut = @AdminRoleId OUTPUT;

IF @AdminRoleId IS NULL
    THROW 50011, N'Nie udało się utworzyć/odczytać roli Admin.', 1;

/* ---------------------------------------------------------------------------
   2. Users u1 and a1 (AspNetUsers).
   --------------------------------------------------------------------------- */
DECLARE @UserTable nvarchar(300) = @SchemaPrefix + N'[AspNetUsers]';

IF NOT EXISTS (SELECT 1 FROM sys.tables t WHERE t.object_id = OBJECT_ID(@UserTable, N'U'))
    THROW 50012, N'Tabela AspNetUsers nie istnieje - uruchom najpierw migracje EF Core.', 1;

DECLARE @UserSql nvarchar(max) = N'
DECLARE @Now datetime2 = SYSUTCDATETIME();

MERGE ' + @UserTable + N' AS target
USING (VALUES
    (N''u1'', N''u1@hogwart.edu.pl''),
    (N''a1'', N''a1@hogwart.edu.pl'')
) AS src ([UserName], [Email])
ON target.[NormalizedUserName] = UPPER(src.[UserName])
WHEN NOT MATCHED THEN
    INSERT ([UserName], [NormalizedUserName], [Email], [NormalizedEmail],
            [EmailConfirmed], [PasswordHash], [SecurityStamp], [ConcurrencyStamp],
            [PhoneNumberConfirmed], [TwoFactorEnabled], [LockoutEnabled], [AccessFailedCount],
            [CreatedAt], [IsVisible], [DisplayEmail], [DisplayPhone], [DisplayWhatsapp],
            [DisplayMessenger], [DisplayInstagram])
    VALUES (src.[UserName], UPPER(src.[UserName]), src.[Email], UPPER(src.[Email]),
            1, @PwdHash, LOWER(CONVERT(nvarchar(36), NEWID())), LOWER(CONVERT(nvarchar(36), NEWID())),
            0, 0, 0, 0,
            @Now, 1, 1, 0, 0,
            0, 0)
WHEN MATCHED AND target.[PasswordHash] IS NULL THEN
    UPDATE SET target.[PasswordHash] = @PwdHash;
';
EXEC sys.sp_executesql @UserSql, N'@PwdHash nvarchar(max)', @PwdHash = @PasswordHash;

/* ---------------------------------------------------------------------------
   3. a1 -> Admin role (AspNetUserRoles).
   --------------------------------------------------------------------------- */
DECLARE @UserRoleTable nvarchar(300) = @SchemaPrefix + N'[AspNetUserRoles]';

IF NOT EXISTS (SELECT 1 FROM sys.tables t WHERE t.object_id = OBJECT_ID(@UserRoleTable, N'U'))
    THROW 50013, N'Tabela AspNetUserRoles nie istnieje - uruchom najpierw migracje EF Core.', 1;

DECLARE @AssignSql nvarchar(max) = N'
DECLARE @A1Id int;
SELECT @A1Id = [Id] FROM ' + @UserTable + N' WHERE [NormalizedUserName] = N''A1'';

IF @A1Id IS NULL
    THROW 50014, N''Użytkownik a1 nie istnieje po MERGE - błąd skryptu.'', 1;

IF NOT EXISTS (SELECT 1 FROM ' + @UserRoleTable + N' WHERE [UserId] = @A1Id AND [RoleId] = @RoleId)
    INSERT INTO ' + @UserRoleTable + N' ([UserId], [RoleId]) VALUES (@A1Id, @RoleId);
';
EXEC sys.sp_executesql @AssignSql, N'@RoleId int', @RoleId = @AdminRoleId;

COMMIT TRANSACTION;

PRINT N'Użytkownicy u1 i a1 dodani (hasło: TestPass123!). a1 ma rolę Admin.';
