// <auto-generated />
using System;
using Booker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Booker.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241219201104_CompleteSeed")]
    partial class CompleteSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Booker.Data.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Level")
                        .HasColumnType("bit");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Grade = "1",
                            Level = true,
                            Subject = "Polski",
                            Title = "Ponad słowami 1 cz. 1"
                        },
                        new
                        {
                            Id = 2,
                            Grade = "1",
                            Level = true,
                            Subject = "Polski",
                            Title = "Ponad słowami 1 cz. 2"
                        },
                        new
                        {
                            Id = 3,
                            Grade = "2",
                            Level = true,
                            Subject = "Polski",
                            Title = "Ponad słowami 2 cz. 1"
                        },
                        new
                        {
                            Id = 4,
                            Grade = "2/3",
                            Level = true,
                            Subject = "Polski",
                            Title = "Ponad słowami 2 cz. 2"
                        },
                        new
                        {
                            Id = 5,
                            Grade = "3",
                            Level = true,
                            Subject = "Polski",
                            Title = "Ponad słowami 3 cz. 1"
                        },
                        new
                        {
                            Id = 6,
                            Grade = "4",
                            Level = true,
                            Subject = "Polski",
                            Title = "Ponad słowami 3 cz. 2"
                        },
                        new
                        {
                            Id = 7,
                            Grade = "5",
                            Level = true,
                            Subject = "Polski",
                            Title = "Ponad słowami 4"
                        },
                        new
                        {
                            Id = 8,
                            Grade = "Zależnie od poziomu",
                            Level = true,
                            Subject = "Język angielski",
                            Title = "Focus 2 Podręcznik"
                        },
                        new
                        {
                            Id = 9,
                            Grade = "Zależnie od poziomu",
                            Level = true,
                            Subject = "Język angielski",
                            Title = "Focus 3 Podręcznik"
                        },
                        new
                        {
                            Id = 10,
                            Grade = "Zależnie od poziomu",
                            Level = true,
                            Subject = "Język angielski",
                            Title = "Focus 4 Podręcznik"
                        },
                        new
                        {
                            Id = 11,
                            Grade = "Zależnie od poziomu",
                            Level = true,
                            Subject = "Język angielski",
                            Title = "Focus 5 Podręcznik"
                        },
                        new
                        {
                            Id = 12,
                            Grade = "Zależnie od poziomu",
                            Level = true,
                            Subject = "Język angielski",
                            Title = "Focus 2 Ćwiczenia"
                        },
                        new
                        {
                            Id = 13,
                            Grade = "Zależnie od poziomu",
                            Level = true,
                            Subject = "Język angielski",
                            Title = "Focus 3 Ćwiczenia"
                        },
                        new
                        {
                            Id = 14,
                            Grade = "Zależnie od poziomu",
                            Level = true,
                            Subject = "Język angielski",
                            Title = "Focus 4 Ćwiczenia"
                        },
                        new
                        {
                            Id = 15,
                            Grade = "Zależnie od poziomu",
                            Level = true,
                            Subject = "Język angielski",
                            Title = "Focus 5 Ćwiczenia"
                        },
                        new
                        {
                            Id = 16,
                            Grade = "4",
                            Level = true,
                            Subject = "Język angielski",
                            Title = "My matura perspectives [nowa era]"
                        },
                        new
                        {
                            Id = 17,
                            Grade = "5",
                            Level = true,
                            Subject = "Język angielski",
                            Title = "Repetytorium [Macmillan]"
                        },
                        new
                        {
                            Id = 18,
                            Grade = "5",
                            Level = false,
                            Subject = "Język angielski",
                            Title = "Repetytorium maturzysty [Oxford]"
                        },
                        new
                        {
                            Id = 19,
                            Grade = "5",
                            Level = true,
                            Subject = "Język angielski",
                            Title = "Repetytorium maturzysty [Cambridge, PWN]"
                        },
                        new
                        {
                            Id = 20,
                            Grade = "1",
                            Level = true,
                            Subject = "Język Niemiecki",
                            Title = "Welttour Deutsch 1"
                        },
                        new
                        {
                            Id = 21,
                            Grade = "2",
                            Level = true,
                            Subject = "Język Niemiecki",
                            Title = "Welttour Deutsch 2"
                        },
                        new
                        {
                            Id = 22,
                            Grade = "3",
                            Level = true,
                            Subject = "Język Niemiecki",
                            Title = "Welttour Deutsch 3"
                        },
                        new
                        {
                            Id = 23,
                            Grade = "4/5",
                            Level = true,
                            Subject = "Język Niemiecki",
                            Title = "Welttour Deutsch 4"
                        },
                        new
                        {
                            Id = 24,
                            Grade = "1",
                            Level = true,
                            Subject = "Język Niemiecki",
                            Title = "Effekt 1"
                        },
                        new
                        {
                            Id = 25,
                            Grade = "2",
                            Level = true,
                            Subject = "Język Niemiecki",
                            Title = "Effekt 2"
                        },
                        new
                        {
                            Id = 26,
                            Grade = "3",
                            Level = true,
                            Subject = "Język Niemiecki",
                            Title = "Effekt 3"
                        },
                        new
                        {
                            Id = 27,
                            Grade = "4/5",
                            Level = true,
                            Subject = "Język Niemiecki",
                            Title = "Effekt 4"
                        },
                        new
                        {
                            Id = 28,
                            Grade = "1",
                            Level = true,
                            Subject = "Biologia",
                            Title = "Biologia na czasie 1"
                        },
                        new
                        {
                            Id = 29,
                            Grade = "2/3",
                            Level = true,
                            Subject = "Biologia",
                            Title = "Biologia na czasie 2"
                        },
                        new
                        {
                            Id = 30,
                            Grade = "4",
                            Level = true,
                            Subject = "Biologia",
                            Title = "Biologia na czasie 3"
                        },
                        new
                        {
                            Id = 31,
                            Grade = "1",
                            Level = false,
                            Subject = "Biologia",
                            Title = "Biologia na czasie 1"
                        },
                        new
                        {
                            Id = 32,
                            Grade = "2",
                            Level = false,
                            Subject = "Biologia",
                            Title = "Biologia na czasie 2"
                        },
                        new
                        {
                            Id = 33,
                            Grade = "3/4",
                            Level = false,
                            Subject = "Biologia",
                            Title = "Biologia na czasie 3"
                        },
                        new
                        {
                            Id = 34,
                            Grade = "1,2,3",
                            Level = true,
                            Subject = "Chemia",
                            Title = "To jest chemia 1"
                        },
                        new
                        {
                            Id = 35,
                            Grade = "4",
                            Level = true,
                            Subject = "Chemia",
                            Title = "To jest chemia 2"
                        },
                        new
                        {
                            Id = 36,
                            Grade = "1,2,3",
                            Level = false,
                            Subject = "Chemia",
                            Title = "To jest chemia 1"
                        },
                        new
                        {
                            Id = 37,
                            Grade = "4,5",
                            Level = false,
                            Subject = "Chemia",
                            Title = "To jest chemia 2"
                        },
                        new
                        {
                            Id = 38,
                            Grade = "1",
                            Level = true,
                            Subject = "EDB",
                            Title = "Edukacja dla bezpieczeństwa [wsip]"
                        },
                        new
                        {
                            Id = 39,
                            Grade = "1",
                            Level = false,
                            Subject = "Fizyka",
                            Title = "Fizyka 1 [wsip]"
                        },
                        new
                        {
                            Id = 40,
                            Grade = "2",
                            Level = false,
                            Subject = "Fizyka",
                            Title = "Fizyka 2 [wsip]"
                        },
                        new
                        {
                            Id = 41,
                            Grade = "3",
                            Level = false,
                            Subject = "Fizyka",
                            Title = "Fizyka 3 [wsip]"
                        },
                        new
                        {
                            Id = 42,
                            Grade = "4/5",
                            Level = false,
                            Subject = "Fizyka",
                            Title = "Fizyka 4 [wsip]"
                        },
                        new
                        {
                            Id = 43,
                            Grade = "1",
                            Level = true,
                            Subject = "Fizyka",
                            Title = "Fizyka 1 [wsip]"
                        },
                        new
                        {
                            Id = 44,
                            Grade = "2",
                            Level = true,
                            Subject = "Fizyka",
                            Title = "Fizyka 2 [wsip]"
                        },
                        new
                        {
                            Id = 45,
                            Grade = "3",
                            Level = true,
                            Subject = "Fizyka",
                            Title = "Fizyka 3 [wsip]"
                        },
                        new
                        {
                            Id = 46,
                            Grade = "4/5",
                            Level = true,
                            Subject = "Fizyka",
                            Title = "Fizyka 4 [wsip]"
                        },
                        new
                        {
                            Id = 47,
                            Grade = "1/2",
                            Level = true,
                            Subject = "Geografia",
                            Title = "Oblicza geografii 1"
                        },
                        new
                        {
                            Id = 48,
                            Grade = "3/4",
                            Level = true,
                            Subject = "Geografia",
                            Title = "Oblicza geografii 2"
                        },
                        new
                        {
                            Id = 49,
                            Grade = "1/2",
                            Level = true,
                            Subject = "Geografia",
                            Title = "Oblicz geografii karty pracy 1"
                        },
                        new
                        {
                            Id = 50,
                            Grade = "3/4",
                            Level = true,
                            Subject = "Geografia",
                            Title = "Oblicz geografii karty pracy 2"
                        },
                        new
                        {
                            Id = 51,
                            Grade = "1",
                            Level = true,
                            Subject = "Historia",
                            Title = "Historia [wsip] 1"
                        },
                        new
                        {
                            Id = 52,
                            Grade = "2",
                            Level = true,
                            Subject = "Historia",
                            Title = "Historia [wsip] 2"
                        },
                        new
                        {
                            Id = 53,
                            Grade = "3",
                            Level = true,
                            Subject = "Historia",
                            Title = "Historia [wsip] 3"
                        },
                        new
                        {
                            Id = 54,
                            Grade = "4",
                            Level = true,
                            Subject = "Historia",
                            Title = "Historia [wsip] 4"
                        },
                        new
                        {
                            Id = 55,
                            Grade = "2",
                            Level = true,
                            Subject = "HiT",
                            Title = "Historia i teraźniejszość [wsip] 1"
                        },
                        new
                        {
                            Id = 56,
                            Grade = "3",
                            Level = true,
                            Subject = "HiT",
                            Title = "Historia i teraźniejszość [wsip] 2"
                        },
                        new
                        {
                            Id = 57,
                            Grade = "1/2",
                            Level = true,
                            Subject = "Informatyka",
                            Title = "Informatyka [operon]"
                        },
                        new
                        {
                            Id = 58,
                            Grade = "3/4",
                            Level = true,
                            Subject = "Informatyka",
                            Title = "Informatyka dla szkół ponadgimnazjalnych [Migra]"
                        },
                        new
                        {
                            Id = 59,
                            Grade = "1/2",
                            Level = false,
                            Subject = "Informatyka",
                            Title = "Informatyka [operon]"
                        },
                        new
                        {
                            Id = 60,
                            Grade = "3/4",
                            Level = false,
                            Subject = "Informatyka",
                            Title = "Informatyka dla szkół ponadgimnazjalnych [Migra]"
                        },
                        new
                        {
                            Id = 61,
                            Grade = "1/2",
                            Level = true,
                            Subject = "Matematyka",
                            Title = "NOWA MATeMAtyka 1"
                        },
                        new
                        {
                            Id = 62,
                            Grade = "2/3",
                            Level = true,
                            Subject = "Matematyka",
                            Title = "NOWA MATeMAtyka 2"
                        },
                        new
                        {
                            Id = 63,
                            Grade = "3/4",
                            Level = true,
                            Subject = "Matematyka",
                            Title = "NOWA MATeMAtyka 3"
                        },
                        new
                        {
                            Id = 64,
                            Grade = "4/5",
                            Level = true,
                            Subject = "Matematyka",
                            Title = "NOWA MATeMAtyka 4"
                        },
                        new
                        {
                            Id = 65,
                            Grade = "1/2",
                            Level = false,
                            Subject = "Matematyka",
                            Title = "NOWA MATeMAtyka 1"
                        },
                        new
                        {
                            Id = 66,
                            Grade = "2/3",
                            Level = false,
                            Subject = "Matematyka",
                            Title = "NOWA MATeMAtyka 2"
                        },
                        new
                        {
                            Id = 67,
                            Grade = "3/4",
                            Level = false,
                            Subject = "Matematyka",
                            Title = "NOWA MATeMAtyka 3"
                        },
                        new
                        {
                            Id = 68,
                            Grade = "4/5",
                            Level = false,
                            Subject = "Matematyka",
                            Title = "NOWA MATeMAtyka 4"
                        },
                        new
                        {
                            Id = 69,
                            Grade = "2/3",
                            Level = true,
                            Subject = "Podstawy przedsiębiorczości",
                            Title = "Krok w przedsiębiorczość"
                        },
                        new
                        {
                            Id = 70,
                            Grade = "1",
                            Level = true,
                            Subject = "Biznes i zarządzanie",
                            Title = "Krok w biznes i zarządzanie 1"
                        },
                        new
                        {
                            Id = 71,
                            Grade = "2",
                            Level = true,
                            Subject = "Biznes i zarządzanie",
                            Title = "Krok w biznes i zarządzanie 2"
                        },
                        new
                        {
                            Id = 72,
                            Grade = "1",
                            Level = true,
                            Subject = "Plastyka",
                            Title = "Spotkania ze sztuką 1"
                        },
                        new
                        {
                            Id = 73,
                            Grade = "4",
                            Level = true,
                            Subject = "WOS",
                            Title = "W centrum uwagi 1"
                        },
                        new
                        {
                            Id = 74,
                            Grade = "5",
                            Level = true,
                            Subject = "WOS",
                            Title = "W centrum uwagi 2"
                        },
                        new
                        {
                            Id = 75,
                            Grade = "3/4",
                            Level = false,
                            Subject = "Angielski zawodowy",
                            Title = "Electronics"
                        },
                        new
                        {
                            Id = 76,
                            Grade = "3/4",
                            Level = false,
                            Subject = "Angielski zawodowy",
                            Title = "Electrician"
                        },
                        new
                        {
                            Id = 77,
                            Grade = "3/4",
                            Level = false,
                            Subject = "Angielski zawodowy",
                            Title = "Software engineering"
                        },
                        new
                        {
                            Id = 78,
                            Grade = "3/4",
                            Level = false,
                            Subject = "Angielski zawodowy",
                            Title = "Computing"
                        },
                        new
                        {
                            Id = 79,
                            Grade = "3/4",
                            Level = false,
                            Subject = "Angielski zawodowy",
                            Title = "Mechanical engineering"
                        },
                        new
                        {
                            Id = 80,
                            Grade = "3/4",
                            Level = false,
                            Subject = "Angielski zawodowy",
                            Title = "Mechanics"
                        },
                        new
                        {
                            Id = 81,
                            Grade = "3/4",
                            Level = false,
                            Subject = "Angielski zawodowy",
                            Title = "Enviromental Science"
                        });
                });

            modelBuilder.Entity("Booker.Data.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserID");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 68,
                            DateTime = new DateTime(2024, 12, 19, 21, 11, 4, 454, DateTimeKind.Local).AddTicks(9506),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 23.142857142857142857142857143m,
                            State = "bardzo dobry",
                            UserID = 1
                        },
                        new
                        {
                            Id = 2,
                            BookId = 59,
                            DateTime = new DateTime(2024, 12, 19, 21, 11, 4, 454, DateTimeKind.Local).AddTicks(9563),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 36.285714285714285714285714286m,
                            State = "bardzo dobry",
                            UserID = 2
                        },
                        new
                        {
                            Id = 3,
                            BookId = 64,
                            DateTime = new DateTime(2024, 12, 19, 21, 11, 4, 454, DateTimeKind.Local).AddTicks(9569),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 62.714285714285714285714285714m,
                            State = "bardzo dobry",
                            UserID = 3
                        },
                        new
                        {
                            Id = 4,
                            BookId = 48,
                            DateTime = new DateTime(2024, 12, 19, 21, 11, 4, 454, DateTimeKind.Local).AddTicks(9572),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 48.857142857142857142857142857m,
                            State = "bardzo dobry",
                            UserID = 4
                        },
                        new
                        {
                            Id = 5,
                            BookId = 12,
                            DateTime = new DateTime(2024, 12, 19, 21, 11, 4, 454, DateTimeKind.Local).AddTicks(9575),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 32.857142857142857142857142857m,
                            State = "bardzo dobry",
                            UserID = 5
                        },
                        new
                        {
                            Id = 6,
                            BookId = 60,
                            DateTime = new DateTime(2024, 12, 19, 21, 11, 4, 454, DateTimeKind.Local).AddTicks(9579),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 79m,
                            State = "bardzo dobry",
                            UserID = 1
                        },
                        new
                        {
                            Id = 7,
                            BookId = 50,
                            DateTime = new DateTime(2024, 12, 19, 21, 11, 4, 454, DateTimeKind.Local).AddTicks(9582),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 24.714285714285714285714285714m,
                            State = "bardzo dobry",
                            UserID = 2
                        },
                        new
                        {
                            Id = 8,
                            BookId = 22,
                            DateTime = new DateTime(2024, 12, 19, 21, 11, 4, 454, DateTimeKind.Local).AddTicks(9586),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 77.714285714285714285714285714m,
                            State = "bardzo dobry",
                            UserID = 3
                        },
                        new
                        {
                            Id = 9,
                            BookId = 14,
                            DateTime = new DateTime(2024, 12, 19, 21, 11, 4, 454, DateTimeKind.Local).AddTicks(9590),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 82.85714285714285714285714286m,
                            State = "bardzo dobry",
                            UserID = 4
                        },
                        new
                        {
                            Id = 10,
                            BookId = 17,
                            DateTime = new DateTime(2024, 12, 19, 21, 11, 4, 454, DateTimeKind.Local).AddTicks(9593),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 36.571428571428571428571428571m,
                            State = "bardzo dobry",
                            UserID = 5
                        },
                        new
                        {
                            Id = 11,
                            BookId = 51,
                            DateTime = new DateTime(2024, 12, 19, 21, 11, 4, 454, DateTimeKind.Local).AddTicks(9596),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 76.857142857142857142857142857m,
                            State = "bardzo dobry",
                            UserID = 1
                        },
                        new
                        {
                            Id = 12,
                            BookId = 57,
                            DateTime = new DateTime(2024, 12, 19, 21, 11, 4, 454, DateTimeKind.Local).AddTicks(9600),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 62.285714285714285714285714286m,
                            State = "bardzo dobry",
                            UserID = 2
                        },
                        new
                        {
                            Id = 13,
                            BookId = 19,
                            DateTime = new DateTime(2024, 12, 19, 21, 11, 4, 454, DateTimeKind.Local).AddTicks(9603),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 20.285714285714285714285714286m,
                            State = "bardzo dobry",
                            UserID = 3
                        },
                        new
                        {
                            Id = 14,
                            BookId = 23,
                            DateTime = new DateTime(2024, 12, 19, 21, 11, 4, 454, DateTimeKind.Local).AddTicks(9606),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 53.714285714285714285714285714m,
                            State = "bardzo dobry",
                            UserID = 4
                        },
                        new
                        {
                            Id = 15,
                            BookId = 60,
                            DateTime = new DateTime(2024, 12, 19, 21, 11, 4, 454, DateTimeKind.Local).AddTicks(9609),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 54.142857142857142857142857143m,
                            State = "bardzo dobry",
                            UserID = 5
                        },
                        new
                        {
                            Id = 16,
                            BookId = 36,
                            DateTime = new DateTime(2024, 12, 19, 21, 11, 4, 454, DateTimeKind.Local).AddTicks(9613),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 49.285714285714285714285714286m,
                            State = "bardzo dobry",
                            UserID = 1
                        },
                        new
                        {
                            Id = 17,
                            BookId = 69,
                            DateTime = new DateTime(2024, 12, 19, 21, 11, 4, 454, DateTimeKind.Local).AddTicks(9616),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 49.571428571428571428571428571m,
                            State = "bardzo dobry",
                            UserID = 2
                        },
                        new
                        {
                            Id = 18,
                            BookId = 70,
                            DateTime = new DateTime(2024, 12, 19, 21, 11, 4, 454, DateTimeKind.Local).AddTicks(9619),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 55m,
                            State = "bardzo dobry",
                            UserID = 3
                        },
                        new
                        {
                            Id = 19,
                            BookId = 27,
                            DateTime = new DateTime(2024, 12, 19, 21, 11, 4, 454, DateTimeKind.Local).AddTicks(9622),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 58.857142857142857142857142857m,
                            State = "bardzo dobry",
                            UserID = 4
                        },
                        new
                        {
                            Id = 20,
                            BookId = 17,
                            DateTime = new DateTime(2024, 12, 19, 21, 11, 4, 454, DateTimeKind.Local).AddTicks(9625),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 72.428571428571428571428571429m,
                            State = "bardzo dobry",
                            UserID = 5
                        },
                        new
                        {
                            Id = 21,
                            BookId = 79,
                            DateTime = new DateTime(2024, 12, 19, 21, 11, 4, 454, DateTimeKind.Local).AddTicks(9628),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 83.28571428571428571428571429m,
                            State = "bardzo dobry",
                            UserID = 1
                        },
                        new
                        {
                            Id = 22,
                            BookId = 44,
                            DateTime = new DateTime(2024, 12, 19, 21, 11, 4, 454, DateTimeKind.Local).AddTicks(9631),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 50.571428571428571428571428571m,
                            State = "bardzo dobry",
                            UserID = 2
                        },
                        new
                        {
                            Id = 23,
                            BookId = 23,
                            DateTime = new DateTime(2024, 12, 19, 21, 11, 4, 454, DateTimeKind.Local).AddTicks(9635),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 53m,
                            State = "bardzo dobry",
                            UserID = 3
                        },
                        new
                        {
                            Id = 24,
                            BookId = 30,
                            DateTime = new DateTime(2024, 12, 19, 21, 11, 4, 454, DateTimeKind.Local).AddTicks(9638),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 78.428571428571428571428571429m,
                            State = "bardzo dobry",
                            UserID = 4
                        },
                        new
                        {
                            Id = 25,
                            BookId = 42,
                            DateTime = new DateTime(2024, 12, 19, 21, 11, 4, 454, DateTimeKind.Local).AddTicks(9641),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 83.14285714285714285714285714m,
                            State = "bardzo dobry",
                            UserID = 5
                        },
                        new
                        {
                            Id = 26,
                            BookId = 11,
                            DateTime = new DateTime(2024, 12, 19, 21, 11, 4, 454, DateTimeKind.Local).AddTicks(9644),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 35.857142857142857142857142857m,
                            State = "bardzo dobry",
                            UserID = 1
                        },
                        new
                        {
                            Id = 27,
                            BookId = 29,
                            DateTime = new DateTime(2024, 12, 19, 21, 11, 4, 454, DateTimeKind.Local).AddTicks(9648),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 42.142857142857142857142857143m,
                            State = "bardzo dobry",
                            UserID = 2
                        },
                        new
                        {
                            Id = 28,
                            BookId = 51,
                            DateTime = new DateTime(2024, 12, 19, 21, 11, 4, 454, DateTimeKind.Local).AddTicks(9651),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 70.285714285714285714285714286m,
                            State = "bardzo dobry",
                            UserID = 3
                        },
                        new
                        {
                            Id = 29,
                            BookId = 19,
                            DateTime = new DateTime(2024, 12, 19, 21, 11, 4, 454, DateTimeKind.Local).AddTicks(9654),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 73.142857142857142857142857143m,
                            State = "bardzo dobry",
                            UserID = 4
                        },
                        new
                        {
                            Id = 30,
                            BookId = 49,
                            DateTime = new DateTime(2024, 12, 19, 21, 11, 4, 454, DateTimeKind.Local).AddTicks(9657),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 52m,
                            State = "bardzo dobry",
                            UserID = 5
                        },
                        new
                        {
                            Id = 31,
                            BookId = 56,
                            DateTime = new DateTime(2024, 12, 19, 21, 11, 4, 454, DateTimeKind.Local).AddTicks(9660),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 32m,
                            State = "bardzo dobry",
                            UserID = 1
                        },
                        new
                        {
                            Id = 32,
                            BookId = 79,
                            DateTime = new DateTime(2024, 12, 19, 21, 11, 4, 454, DateTimeKind.Local).AddTicks(9663),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 33.857142857142857142857142857m,
                            State = "bardzo dobry",
                            UserID = 2
                        },
                        new
                        {
                            Id = 33,
                            BookId = 19,
                            DateTime = new DateTime(2024, 12, 19, 21, 11, 4, 454, DateTimeKind.Local).AddTicks(9667),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 80m,
                            State = "bardzo dobry",
                            UserID = 3
                        },
                        new
                        {
                            Id = 34,
                            BookId = 24,
                            DateTime = new DateTime(2024, 12, 19, 21, 11, 4, 454, DateTimeKind.Local).AddTicks(9670),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 34m,
                            State = "bardzo dobry",
                            UserID = 4
                        },
                        new
                        {
                            Id = 35,
                            BookId = 29,
                            DateTime = new DateTime(2024, 12, 19, 21, 11, 4, 454, DateTimeKind.Local).AddTicks(9672),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 42m,
                            State = "bardzo dobry",
                            UserID = 5
                        },
                        new
                        {
                            Id = 36,
                            BookId = 6,
                            DateTime = new DateTime(2024, 12, 19, 21, 11, 4, 454, DateTimeKind.Local).AddTicks(9676),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 30.857142857142857142857142857m,
                            State = "bardzo dobry",
                            UserID = 1
                        },
                        new
                        {
                            Id = 37,
                            BookId = 62,
                            DateTime = new DateTime(2024, 12, 19, 21, 11, 4, 454, DateTimeKind.Local).AddTicks(9679),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 29.285714285714285714285714286m,
                            State = "bardzo dobry",
                            UserID = 2
                        });
                });

            modelBuilder.Entity("Booker.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("School")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "user1@gmail.com",
                            Nickname = "user1",
                            Password = "zaq1@WSX",
                            Photo = "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png",
                            School = "Śl.TZN"
                        },
                        new
                        {
                            Id = 2,
                            Email = "user2@gmail.com",
                            Nickname = "user2",
                            Password = "zaq1@WSX",
                            Photo = "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png",
                            School = "Śl.TZN"
                        },
                        new
                        {
                            Id = 3,
                            Email = "user3@gmail.com",
                            Nickname = "user3",
                            Password = "zaq1@WSX",
                            Photo = "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png",
                            School = "Śl.TZN"
                        },
                        new
                        {
                            Id = 4,
                            Email = "user4@gmail.com",
                            Nickname = "user4",
                            Password = "zaq1@WSX",
                            Photo = "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png",
                            School = "Śl.TZN"
                        },
                        new
                        {
                            Id = 5,
                            Email = "user5@gmail.com",
                            Nickname = "user5",
                            Password = "zaq1@WSX",
                            Photo = "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png",
                            School = "Śl.TZN"
                        });
                });

            modelBuilder.Entity("Booker.Data.Item", b =>
                {
                    b.HasOne("Booker.Data.Book", "Book")
                        .WithMany("Items")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Booker.Data.User", "User")
                        .WithMany("Items")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Booker.Data.Book", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Booker.Data.User", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
