// <auto-generated />
using System;
using Booker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Booker.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250123173657_IdentityStart")]
    partial class IdentityStart
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Booker.Data.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Level")
                        .HasColumnType("bit");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Level = true,
                            Subject = "Polski",
                            Title = "Ponad słowami 1 cz. 1"
                        },
                        new
                        {
                            Id = 2,
                            Level = true,
                            Subject = "Polski",
                            Title = "Ponad słowami 1 cz. 2"
                        },
                        new
                        {
                            Id = 3,
                            Level = true,
                            Subject = "Polski",
                            Title = "Ponad słowami 2 cz. 1"
                        },
                        new
                        {
                            Id = 4,
                            Level = true,
                            Subject = "Polski",
                            Title = "Ponad słowami 2 cz. 2"
                        },
                        new
                        {
                            Id = 5,
                            Level = true,
                            Subject = "Polski",
                            Title = "Ponad słowami 3 cz. 1"
                        },
                        new
                        {
                            Id = 6,
                            Level = true,
                            Subject = "Polski",
                            Title = "Ponad słowami 3 cz. 2"
                        },
                        new
                        {
                            Id = 7,
                            Level = true,
                            Subject = "Polski",
                            Title = "Ponad słowami 4"
                        },
                        new
                        {
                            Id = 8,
                            Level = true,
                            Subject = "Język angielski",
                            Title = "Focus 2 Podręcznik"
                        },
                        new
                        {
                            Id = 9,
                            Level = true,
                            Subject = "Język angielski",
                            Title = "Focus 3 Podręcznik"
                        },
                        new
                        {
                            Id = 10,
                            Level = true,
                            Subject = "Język angielski",
                            Title = "Focus 4 Podręcznik"
                        },
                        new
                        {
                            Id = 11,
                            Level = true,
                            Subject = "Język angielski",
                            Title = "Focus 5 Podręcznik"
                        },
                        new
                        {
                            Id = 12,
                            Level = true,
                            Subject = "Język angielski",
                            Title = "Focus 2 Ćwiczenia"
                        },
                        new
                        {
                            Id = 13,
                            Level = true,
                            Subject = "Język angielski",
                            Title = "Focus 3 Ćwiczenia"
                        },
                        new
                        {
                            Id = 14,
                            Level = true,
                            Subject = "Język angielski",
                            Title = "Focus 4 Ćwiczenia"
                        },
                        new
                        {
                            Id = 15,
                            Level = true,
                            Subject = "Język angielski",
                            Title = "Focus 5 Ćwiczenia"
                        },
                        new
                        {
                            Id = 16,
                            Level = true,
                            Subject = "Język angielski",
                            Title = "My matura perspectives [nowa era]"
                        },
                        new
                        {
                            Id = 17,
                            Level = true,
                            Subject = "Język angielski",
                            Title = "Repetytorium [Macmillan]"
                        },
                        new
                        {
                            Id = 18,
                            Level = false,
                            Subject = "Język angielski",
                            Title = "Repetytorium maturzysty [Oxford]"
                        },
                        new
                        {
                            Id = 19,
                            Level = true,
                            Subject = "Język angielski",
                            Title = "Repetytorium maturzysty [Cambridge, PWN]"
                        },
                        new
                        {
                            Id = 20,
                            Level = true,
                            Subject = "Język Niemiecki",
                            Title = "Welttour Deutsch 1"
                        },
                        new
                        {
                            Id = 21,
                            Level = true,
                            Subject = "Język Niemiecki",
                            Title = "Welttour Deutsch 2"
                        },
                        new
                        {
                            Id = 22,
                            Level = true,
                            Subject = "Język Niemiecki",
                            Title = "Welttour Deutsch 3"
                        },
                        new
                        {
                            Id = 23,
                            Level = true,
                            Subject = "Język Niemiecki",
                            Title = "Welttour Deutsch 4"
                        },
                        new
                        {
                            Id = 24,
                            Level = true,
                            Subject = "Język Niemiecki",
                            Title = "Effekt 1"
                        },
                        new
                        {
                            Id = 25,
                            Level = true,
                            Subject = "Język Niemiecki",
                            Title = "Effekt 2"
                        },
                        new
                        {
                            Id = 26,
                            Level = true,
                            Subject = "Język Niemiecki",
                            Title = "Effekt 3"
                        },
                        new
                        {
                            Id = 27,
                            Level = true,
                            Subject = "Język Niemiecki",
                            Title = "Effekt 4"
                        },
                        new
                        {
                            Id = 28,
                            Level = true,
                            Subject = "Biologia",
                            Title = "Biologia na czasie 1"
                        },
                        new
                        {
                            Id = 29,
                            Level = true,
                            Subject = "Biologia",
                            Title = "Biologia na czasie 2"
                        },
                        new
                        {
                            Id = 30,
                            Level = true,
                            Subject = "Biologia",
                            Title = "Biologia na czasie 3"
                        },
                        new
                        {
                            Id = 31,
                            Level = false,
                            Subject = "Biologia",
                            Title = "Biologia na czasie 1"
                        },
                        new
                        {
                            Id = 32,
                            Level = false,
                            Subject = "Biologia",
                            Title = "Biologia na czasie 2"
                        },
                        new
                        {
                            Id = 33,
                            Level = false,
                            Subject = "Biologia",
                            Title = "Biologia na czasie 3"
                        },
                        new
                        {
                            Id = 34,
                            Level = true,
                            Subject = "Chemia",
                            Title = "To jest chemia 1"
                        },
                        new
                        {
                            Id = 35,
                            Level = true,
                            Subject = "Chemia",
                            Title = "To jest chemia 2"
                        },
                        new
                        {
                            Id = 36,
                            Level = false,
                            Subject = "Chemia",
                            Title = "To jest chemia 1"
                        },
                        new
                        {
                            Id = 37,
                            Level = false,
                            Subject = "Chemia",
                            Title = "To jest chemia 2"
                        },
                        new
                        {
                            Id = 38,
                            Level = true,
                            Subject = "EDB",
                            Title = "Edukacja dla bezpieczeństwa [wsip]"
                        },
                        new
                        {
                            Id = 39,
                            Level = false,
                            Subject = "Fizyka",
                            Title = "Fizyka 1 [wsip]"
                        },
                        new
                        {
                            Id = 40,
                            Level = false,
                            Subject = "Fizyka",
                            Title = "Fizyka 2 [wsip]"
                        },
                        new
                        {
                            Id = 41,
                            Level = false,
                            Subject = "Fizyka",
                            Title = "Fizyka 3 [wsip]"
                        },
                        new
                        {
                            Id = 42,
                            Level = false,
                            Subject = "Fizyka",
                            Title = "Fizyka 4 [wsip]"
                        },
                        new
                        {
                            Id = 43,
                            Level = true,
                            Subject = "Fizyka",
                            Title = "Fizyka 1 [wsip]"
                        },
                        new
                        {
                            Id = 44,
                            Level = true,
                            Subject = "Fizyka",
                            Title = "Fizyka 2 [wsip]"
                        },
                        new
                        {
                            Id = 45,
                            Level = true,
                            Subject = "Fizyka",
                            Title = "Fizyka 3 [wsip]"
                        },
                        new
                        {
                            Id = 46,
                            Level = true,
                            Subject = "Fizyka",
                            Title = "Fizyka 4 [wsip]"
                        },
                        new
                        {
                            Id = 47,
                            Level = true,
                            Subject = "Geografia",
                            Title = "Oblicza geografii 1"
                        },
                        new
                        {
                            Id = 48,
                            Level = true,
                            Subject = "Geografia",
                            Title = "Oblicza geografii 2"
                        },
                        new
                        {
                            Id = 49,
                            Level = true,
                            Subject = "Geografia",
                            Title = "Oblicz geografii karty pracy 1"
                        },
                        new
                        {
                            Id = 50,
                            Level = true,
                            Subject = "Geografia",
                            Title = "Oblicz geografii karty pracy 2"
                        },
                        new
                        {
                            Id = 51,
                            Level = true,
                            Subject = "Historia",
                            Title = "Historia [wsip] 1"
                        },
                        new
                        {
                            Id = 52,
                            Level = true,
                            Subject = "Historia",
                            Title = "Historia [wsip] 2"
                        },
                        new
                        {
                            Id = 53,
                            Level = true,
                            Subject = "Historia",
                            Title = "Historia [wsip] 3"
                        },
                        new
                        {
                            Id = 54,
                            Level = true,
                            Subject = "Historia",
                            Title = "Historia [wsip] 4"
                        },
                        new
                        {
                            Id = 55,
                            Level = true,
                            Subject = "HiT",
                            Title = "Historia i teraźniejszość [wsip] 1"
                        },
                        new
                        {
                            Id = 56,
                            Level = true,
                            Subject = "HiT",
                            Title = "Historia i teraźniejszość [wsip] 2"
                        },
                        new
                        {
                            Id = 57,
                            Level = true,
                            Subject = "Informatyka",
                            Title = "Informatyka [operon]"
                        },
                        new
                        {
                            Id = 58,
                            Level = true,
                            Subject = "Informatyka",
                            Title = "Informatyka dla szkół ponadgimnazjalnych [Migra]"
                        },
                        new
                        {
                            Id = 59,
                            Level = false,
                            Subject = "Informatyka",
                            Title = "Informatyka [operon]"
                        },
                        new
                        {
                            Id = 60,
                            Level = false,
                            Subject = "Informatyka",
                            Title = "Informatyka dla szkół ponadgimnazjalnych [Migra]"
                        },
                        new
                        {
                            Id = 61,
                            Level = true,
                            Subject = "Matematyka",
                            Title = "NOWA MATeMAtyka 1"
                        },
                        new
                        {
                            Id = 62,
                            Level = true,
                            Subject = "Matematyka",
                            Title = "NOWA MATeMAtyka 2"
                        },
                        new
                        {
                            Id = 63,
                            Level = true,
                            Subject = "Matematyka",
                            Title = "NOWA MATeMAtyka 3"
                        },
                        new
                        {
                            Id = 64,
                            Level = true,
                            Subject = "Matematyka",
                            Title = "NOWA MATeMAtyka 4"
                        },
                        new
                        {
                            Id = 65,
                            Level = false,
                            Subject = "Matematyka",
                            Title = "NOWA MATeMAtyka 1"
                        },
                        new
                        {
                            Id = 66,
                            Level = false,
                            Subject = "Matematyka",
                            Title = "NOWA MATeMAtyka 2"
                        },
                        new
                        {
                            Id = 67,
                            Level = false,
                            Subject = "Matematyka",
                            Title = "NOWA MATeMAtyka 3"
                        },
                        new
                        {
                            Id = 68,
                            Level = false,
                            Subject = "Matematyka",
                            Title = "NOWA MATeMAtyka 4"
                        },
                        new
                        {
                            Id = 69,
                            Level = true,
                            Subject = "Podstawy przedsiębiorczości",
                            Title = "Krok w przedsiębiorczość"
                        },
                        new
                        {
                            Id = 70,
                            Level = true,
                            Subject = "Biznes i zarządzanie",
                            Title = "Krok w biznes i zarządzanie 1"
                        },
                        new
                        {
                            Id = 71,
                            Level = true,
                            Subject = "Biznes i zarządzanie",
                            Title = "Krok w biznes i zarządzanie 2"
                        },
                        new
                        {
                            Id = 72,
                            Level = true,
                            Subject = "Plastyka",
                            Title = "Spotkania ze sztuką 1"
                        },
                        new
                        {
                            Id = 73,
                            Level = true,
                            Subject = "WOS",
                            Title = "W centrum uwagi 1"
                        },
                        new
                        {
                            Id = 74,
                            Level = true,
                            Subject = "WOS",
                            Title = "W centrum uwagi 2"
                        },
                        new
                        {
                            Id = 75,
                            Level = false,
                            Subject = "Angielski zawodowy",
                            Title = "Electronics"
                        },
                        new
                        {
                            Id = 76,
                            Level = false,
                            Subject = "Angielski zawodowy",
                            Title = "Electrician"
                        },
                        new
                        {
                            Id = 77,
                            Level = false,
                            Subject = "Angielski zawodowy",
                            Title = "Software engineering"
                        },
                        new
                        {
                            Id = 78,
                            Level = true,
                            Subject = "Angielski zawodowy",
                            Title = "IT [english for IT]"
                        },
                        new
                        {
                            Id = 79,
                            Level = false,
                            Subject = "Informatyka",
                            Title = "Informatyka w praktyce"
                        });
                });

            modelBuilder.Entity("Booker.Data.BookGrade", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("GradeId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("BookId", "GradeId");

                    b.HasIndex("GradeId");

                    b.ToTable("BookGrades");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            GradeId = "1"
                        },
                        new
                        {
                            BookId = 2,
                            GradeId = "1"
                        },
                        new
                        {
                            BookId = 3,
                            GradeId = "2"
                        },
                        new
                        {
                            BookId = 4,
                            GradeId = "2"
                        },
                        new
                        {
                            BookId = 5,
                            GradeId = "3"
                        },
                        new
                        {
                            BookId = 6,
                            GradeId = "4"
                        },
                        new
                        {
                            BookId = 7,
                            GradeId = "5"
                        },
                        new
                        {
                            BookId = 8,
                            GradeId = "1"
                        },
                        new
                        {
                            BookId = 9,
                            GradeId = "1"
                        },
                        new
                        {
                            BookId = 10,
                            GradeId = "2"
                        },
                        new
                        {
                            BookId = 11,
                            GradeId = "2"
                        },
                        new
                        {
                            BookId = 12,
                            GradeId = "3"
                        },
                        new
                        {
                            BookId = 13,
                            GradeId = "3"
                        },
                        new
                        {
                            BookId = 14,
                            GradeId = "4"
                        },
                        new
                        {
                            BookId = 15,
                            GradeId = "4"
                        },
                        new
                        {
                            BookId = 16,
                            GradeId = "5"
                        },
                        new
                        {
                            BookId = 17,
                            GradeId = "5"
                        },
                        new
                        {
                            BookId = 18,
                            GradeId = "5"
                        },
                        new
                        {
                            BookId = 19,
                            GradeId = "5"
                        },
                        new
                        {
                            BookId = 20,
                            GradeId = "1"
                        },
                        new
                        {
                            BookId = 21,
                            GradeId = "2"
                        },
                        new
                        {
                            BookId = 22,
                            GradeId = "3"
                        },
                        new
                        {
                            BookId = 23,
                            GradeId = "4"
                        },
                        new
                        {
                            BookId = 24,
                            GradeId = "1"
                        },
                        new
                        {
                            BookId = 25,
                            GradeId = "2"
                        },
                        new
                        {
                            BookId = 26,
                            GradeId = "3"
                        },
                        new
                        {
                            BookId = 27,
                            GradeId = "4"
                        },
                        new
                        {
                            BookId = 28,
                            GradeId = "1"
                        },
                        new
                        {
                            BookId = 29,
                            GradeId = "2"
                        },
                        new
                        {
                            BookId = 30,
                            GradeId = "3"
                        },
                        new
                        {
                            BookId = 31,
                            GradeId = "1"
                        },
                        new
                        {
                            BookId = 32,
                            GradeId = "2"
                        },
                        new
                        {
                            BookId = 33,
                            GradeId = "3"
                        },
                        new
                        {
                            BookId = 34,
                            GradeId = "1"
                        },
                        new
                        {
                            BookId = 35,
                            GradeId = "2"
                        },
                        new
                        {
                            BookId = 36,
                            GradeId = "3"
                        },
                        new
                        {
                            BookId = 37,
                            GradeId = "4"
                        },
                        new
                        {
                            BookId = 38,
                            GradeId = "1"
                        },
                        new
                        {
                            BookId = 39,
                            GradeId = "1"
                        },
                        new
                        {
                            BookId = 40,
                            GradeId = "2"
                        },
                        new
                        {
                            BookId = 41,
                            GradeId = "3"
                        },
                        new
                        {
                            BookId = 42,
                            GradeId = "4"
                        },
                        new
                        {
                            BookId = 43,
                            GradeId = "1"
                        },
                        new
                        {
                            BookId = 44,
                            GradeId = "2"
                        },
                        new
                        {
                            BookId = 45,
                            GradeId = "3"
                        },
                        new
                        {
                            BookId = 46,
                            GradeId = "4"
                        },
                        new
                        {
                            BookId = 47,
                            GradeId = "1"
                        },
                        new
                        {
                            BookId = 48,
                            GradeId = "2"
                        },
                        new
                        {
                            BookId = 49,
                            GradeId = "1"
                        },
                        new
                        {
                            BookId = 50,
                            GradeId = "2"
                        },
                        new
                        {
                            BookId = 51,
                            GradeId = "1"
                        },
                        new
                        {
                            BookId = 52,
                            GradeId = "2"
                        },
                        new
                        {
                            BookId = 53,
                            GradeId = "3"
                        },
                        new
                        {
                            BookId = 54,
                            GradeId = "4"
                        },
                        new
                        {
                            BookId = 55,
                            GradeId = "2"
                        },
                        new
                        {
                            BookId = 56,
                            GradeId = "3"
                        },
                        new
                        {
                            BookId = 57,
                            GradeId = "1"
                        },
                        new
                        {
                            BookId = 58,
                            GradeId = "2"
                        },
                        new
                        {
                            BookId = 59,
                            GradeId = "3"
                        },
                        new
                        {
                            BookId = 60,
                            GradeId = "4"
                        },
                        new
                        {
                            BookId = 61,
                            GradeId = "1"
                        },
                        new
                        {
                            BookId = 62,
                            GradeId = "2"
                        },
                        new
                        {
                            BookId = 63,
                            GradeId = "3"
                        },
                        new
                        {
                            BookId = 64,
                            GradeId = "4"
                        },
                        new
                        {
                            BookId = 65,
                            GradeId = "1"
                        },
                        new
                        {
                            BookId = 66,
                            GradeId = "2"
                        },
                        new
                        {
                            BookId = 67,
                            GradeId = "3"
                        },
                        new
                        {
                            BookId = 68,
                            GradeId = "4"
                        },
                        new
                        {
                            BookId = 69,
                            GradeId = "2"
                        },
                        new
                        {
                            BookId = 70,
                            GradeId = "1"
                        },
                        new
                        {
                            BookId = 71,
                            GradeId = "2"
                        },
                        new
                        {
                            BookId = 72,
                            GradeId = "1"
                        },
                        new
                        {
                            BookId = 73,
                            GradeId = "4"
                        },
                        new
                        {
                            BookId = 74,
                            GradeId = "5"
                        },
                        new
                        {
                            BookId = 75,
                            GradeId = "3"
                        },
                        new
                        {
                            BookId = 76,
                            GradeId = "3"
                        },
                        new
                        {
                            BookId = 77,
                            GradeId = "3"
                        },
                        new
                        {
                            BookId = 78,
                            GradeId = "3"
                        });
                });

            modelBuilder.Entity("Booker.Data.Grade", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GradeNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Grades");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            GradeNumber = "1"
                        },
                        new
                        {
                            Id = "2",
                            GradeNumber = "2"
                        },
                        new
                        {
                            Id = "3",
                            GradeNumber = "3"
                        },
                        new
                        {
                            Id = "4",
                            GradeNumber = "4"
                        },
                        new
                        {
                            Id = "5",
                            GradeNumber = "5"
                        });
                });

            modelBuilder.Entity("Booker.Data.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 8,
                            DateTime = new DateTime(2025, 1, 23, 18, 36, 57, 3, DateTimeKind.Local).AddTicks(7517),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 79.142857142857142857142857143m,
                            State = "bardzo dobry",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            BookId = 29,
                            DateTime = new DateTime(2025, 1, 23, 18, 36, 57, 3, DateTimeKind.Local).AddTicks(7581),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 57.571428571428571428571428571m,
                            State = "bardzo dobry",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            BookId = 74,
                            DateTime = new DateTime(2025, 1, 23, 18, 36, 57, 3, DateTimeKind.Local).AddTicks(7587),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 74.142857142857142857142857143m,
                            State = "bardzo dobry",
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            BookId = 35,
                            DateTime = new DateTime(2025, 1, 23, 18, 36, 57, 3, DateTimeKind.Local).AddTicks(7631),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 21.428571428571428571428571429m,
                            State = "bardzo dobry",
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            BookId = 50,
                            DateTime = new DateTime(2025, 1, 23, 18, 36, 57, 3, DateTimeKind.Local).AddTicks(7636),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 22.571428571428571428571428571m,
                            State = "bardzo dobry",
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            BookId = 53,
                            DateTime = new DateTime(2025, 1, 23, 18, 36, 57, 3, DateTimeKind.Local).AddTicks(7642),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 29.285714285714285714285714286m,
                            State = "bardzo dobry",
                            UserId = 1
                        },
                        new
                        {
                            Id = 7,
                            BookId = 4,
                            DateTime = new DateTime(2025, 1, 23, 18, 36, 57, 3, DateTimeKind.Local).AddTicks(7652),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 34.285714285714285714285714286m,
                            State = "bardzo dobry",
                            UserId = 2
                        },
                        new
                        {
                            Id = 8,
                            BookId = 47,
                            DateTime = new DateTime(2025, 1, 23, 18, 36, 57, 3, DateTimeKind.Local).AddTicks(7658),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 20m,
                            State = "bardzo dobry",
                            UserId = 3
                        },
                        new
                        {
                            Id = 9,
                            BookId = 63,
                            DateTime = new DateTime(2025, 1, 23, 18, 36, 57, 3, DateTimeKind.Local).AddTicks(7662),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 63m,
                            State = "bardzo dobry",
                            UserId = 4
                        },
                        new
                        {
                            Id = 10,
                            BookId = 41,
                            DateTime = new DateTime(2025, 1, 23, 18, 36, 57, 3, DateTimeKind.Local).AddTicks(7668),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 77.857142857142857142857142857m,
                            State = "bardzo dobry",
                            UserId = 5
                        },
                        new
                        {
                            Id = 11,
                            BookId = 61,
                            DateTime = new DateTime(2025, 1, 23, 18, 36, 57, 3, DateTimeKind.Local).AddTicks(7673),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 38.571428571428571428571428571m,
                            State = "bardzo dobry",
                            UserId = 1
                        },
                        new
                        {
                            Id = 12,
                            BookId = 4,
                            DateTime = new DateTime(2025, 1, 23, 18, 36, 57, 3, DateTimeKind.Local).AddTicks(7678),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 47.285714285714285714285714286m,
                            State = "bardzo dobry",
                            UserId = 2
                        },
                        new
                        {
                            Id = 13,
                            BookId = 77,
                            DateTime = new DateTime(2025, 1, 23, 18, 36, 57, 3, DateTimeKind.Local).AddTicks(7683),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 38m,
                            State = "bardzo dobry",
                            UserId = 3
                        },
                        new
                        {
                            Id = 14,
                            BookId = 74,
                            DateTime = new DateTime(2025, 1, 23, 18, 36, 57, 3, DateTimeKind.Local).AddTicks(7688),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 42m,
                            State = "bardzo dobry",
                            UserId = 4
                        },
                        new
                        {
                            Id = 15,
                            BookId = 24,
                            DateTime = new DateTime(2025, 1, 23, 18, 36, 57, 3, DateTimeKind.Local).AddTicks(7694),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 23.428571428571428571428571429m,
                            State = "bardzo dobry",
                            UserId = 5
                        },
                        new
                        {
                            Id = 16,
                            BookId = 15,
                            DateTime = new DateTime(2025, 1, 23, 18, 36, 57, 3, DateTimeKind.Local).AddTicks(7700),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 20.714285714285714285714285714m,
                            State = "bardzo dobry",
                            UserId = 1
                        },
                        new
                        {
                            Id = 17,
                            BookId = 66,
                            DateTime = new DateTime(2025, 1, 23, 18, 36, 57, 3, DateTimeKind.Local).AddTicks(7705),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 69.285714285714285714285714286m,
                            State = "bardzo dobry",
                            UserId = 2
                        },
                        new
                        {
                            Id = 18,
                            BookId = 60,
                            DateTime = new DateTime(2025, 1, 23, 18, 36, 57, 3, DateTimeKind.Local).AddTicks(7711),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 77.571428571428571428571428571m,
                            State = "bardzo dobry",
                            UserId = 3
                        },
                        new
                        {
                            Id = 19,
                            BookId = 33,
                            DateTime = new DateTime(2025, 1, 23, 18, 36, 57, 3, DateTimeKind.Local).AddTicks(7715),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 21.285714285714285714285714286m,
                            State = "bardzo dobry",
                            UserId = 4
                        },
                        new
                        {
                            Id = 20,
                            BookId = 74,
                            DateTime = new DateTime(2025, 1, 23, 18, 36, 57, 3, DateTimeKind.Local).AddTicks(7721),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 40.857142857142857142857142857m,
                            State = "bardzo dobry",
                            UserId = 5
                        },
                        new
                        {
                            Id = 21,
                            BookId = 45,
                            DateTime = new DateTime(2025, 1, 23, 18, 36, 57, 3, DateTimeKind.Local).AddTicks(7727),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 82.85714285714285714285714286m,
                            State = "bardzo dobry",
                            UserId = 1
                        },
                        new
                        {
                            Id = 22,
                            BookId = 73,
                            DateTime = new DateTime(2025, 1, 23, 18, 36, 57, 3, DateTimeKind.Local).AddTicks(7733),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 37.428571428571428571428571429m,
                            State = "bardzo dobry",
                            UserId = 2
                        },
                        new
                        {
                            Id = 23,
                            BookId = 3,
                            DateTime = new DateTime(2025, 1, 23, 18, 36, 57, 3, DateTimeKind.Local).AddTicks(7738),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 40.857142857142857142857142857m,
                            State = "bardzo dobry",
                            UserId = 3
                        },
                        new
                        {
                            Id = 24,
                            BookId = 32,
                            DateTime = new DateTime(2025, 1, 23, 18, 36, 57, 3, DateTimeKind.Local).AddTicks(7743),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 27.857142857142857142857142857m,
                            State = "bardzo dobry",
                            UserId = 4
                        },
                        new
                        {
                            Id = 25,
                            BookId = 59,
                            DateTime = new DateTime(2025, 1, 23, 18, 36, 57, 3, DateTimeKind.Local).AddTicks(7748),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 69.714285714285714285714285714m,
                            State = "bardzo dobry",
                            UserId = 5
                        },
                        new
                        {
                            Id = 26,
                            BookId = 10,
                            DateTime = new DateTime(2025, 1, 23, 18, 36, 57, 3, DateTimeKind.Local).AddTicks(7753),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 41.428571428571428571428571429m,
                            State = "bardzo dobry",
                            UserId = 1
                        },
                        new
                        {
                            Id = 27,
                            BookId = 7,
                            DateTime = new DateTime(2025, 1, 23, 18, 36, 57, 3, DateTimeKind.Local).AddTicks(7759),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 29.428571428571428571428571429m,
                            State = "bardzo dobry",
                            UserId = 2
                        },
                        new
                        {
                            Id = 28,
                            BookId = 6,
                            DateTime = new DateTime(2025, 1, 23, 18, 36, 57, 3, DateTimeKind.Local).AddTicks(7764),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 30.714285714285714285714285714m,
                            State = "bardzo dobry",
                            UserId = 3
                        },
                        new
                        {
                            Id = 29,
                            BookId = 36,
                            DateTime = new DateTime(2025, 1, 23, 18, 36, 57, 3, DateTimeKind.Local).AddTicks(7769),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 79.42857142857142857142857143m,
                            State = "bardzo dobry",
                            UserId = 4
                        },
                        new
                        {
                            Id = 30,
                            BookId = 15,
                            DateTime = new DateTime(2025, 1, 23, 18, 36, 57, 3, DateTimeKind.Local).AddTicks(7774),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 84.85714285714285714285714286m,
                            State = "bardzo dobry",
                            UserId = 5
                        },
                        new
                        {
                            Id = 31,
                            BookId = 12,
                            DateTime = new DateTime(2025, 1, 23, 18, 36, 57, 3, DateTimeKind.Local).AddTicks(7779),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 39m,
                            State = "bardzo dobry",
                            UserId = 1
                        },
                        new
                        {
                            Id = 32,
                            BookId = 72,
                            DateTime = new DateTime(2025, 1, 23, 18, 36, 57, 3, DateTimeKind.Local).AddTicks(7784),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 80.14285714285714285714285714m,
                            State = "bardzo dobry",
                            UserId = 2
                        },
                        new
                        {
                            Id = 33,
                            BookId = 75,
                            DateTime = new DateTime(2025, 1, 23, 18, 36, 57, 3, DateTimeKind.Local).AddTicks(7789),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 63m,
                            State = "bardzo dobry",
                            UserId = 3
                        },
                        new
                        {
                            Id = 34,
                            BookId = 25,
                            DateTime = new DateTime(2025, 1, 23, 18, 36, 57, 3, DateTimeKind.Local).AddTicks(7794),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 63.428571428571428571428571429m,
                            State = "bardzo dobry",
                            UserId = 4
                        },
                        new
                        {
                            Id = 35,
                            BookId = 21,
                            DateTime = new DateTime(2025, 1, 23, 18, 36, 57, 3, DateTimeKind.Local).AddTicks(7798),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 44.142857142857142857142857143m,
                            State = "bardzo dobry",
                            UserId = 5
                        },
                        new
                        {
                            Id = 36,
                            BookId = 77,
                            DateTime = new DateTime(2025, 1, 23, 18, 36, 57, 3, DateTimeKind.Local).AddTicks(7803),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 22.142857142857142857142857143m,
                            State = "bardzo dobry",
                            UserId = 1
                        },
                        new
                        {
                            Id = 37,
                            BookId = 10,
                            DateTime = new DateTime(2025, 1, 23, 18, 36, 57, 3, DateTimeKind.Local).AddTicks(7809),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 33.714285714285714285714285714m,
                            State = "bardzo dobry",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Booker.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("School")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "865958b1-4949-45b4-876a-1d5b689c3adb",
                            Email = "user1@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            Photo = "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png",
                            School = "Śl.TZN",
                            TwoFactorEnabled = false,
                            UserName = "user1"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "961a03c8-6368-4537-b9f0-4905b44f1fbb",
                            Email = "user2@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            Photo = "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png",
                            School = "Śl.TZN",
                            TwoFactorEnabled = false,
                            UserName = "user2"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "145d3563-9ee9-4528-8afb-719e0725c863",
                            Email = "user3@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            Photo = "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png",
                            School = "Śl.TZN",
                            TwoFactorEnabled = false,
                            UserName = "user3"
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b78d1dac-7011-4dc8-adc1-f7395a4159cd",
                            Email = "user4@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            Photo = "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png",
                            School = "Śl.TZN",
                            TwoFactorEnabled = false,
                            UserName = "user4"
                        },
                        new
                        {
                            Id = 5,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4af65730-29f6-4ea4-bf9f-4da9dbdd8c4c",
                            Email = "user5@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            Photo = "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png",
                            School = "Śl.TZN",
                            TwoFactorEnabled = false,
                            UserName = "user5"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Booker.Data.BookGrade", b =>
                {
                    b.HasOne("Booker.Data.Book", "Book")
                        .WithMany("BookGrades")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Booker.Data.Grade", "Grade")
                        .WithMany("BookGrades")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Grade");
                });

            modelBuilder.Entity("Booker.Data.Item", b =>
                {
                    b.HasOne("Booker.Data.Book", "Book")
                        .WithMany("Items")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Booker.Data.User", "User")
                        .WithMany("Items")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Booker.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Booker.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Booker.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Booker.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Booker.Data.Book", b =>
                {
                    b.Navigation("BookGrades");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("Booker.Data.Grade", b =>
                {
                    b.Navigation("BookGrades");
                });

            modelBuilder.Entity("Booker.Data.User", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
