// <auto-generated />
using System;
using Booker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Booker.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250111184318_MultiGradeStart")]
    partial class MultiGradeStart
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Booker.Data.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Level")
                        .HasColumnType("bit");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Level = true,
                            Subject = "Polski",
                            Title = "Ponad słowami 1 cz. 1"
                        },
                        new
                        {
                            Id = 2,
                            Level = true,
                            Subject = "Polski",
                            Title = "Ponad słowami 1 cz. 2"
                        },
                        new
                        {
                            Id = 3,
                            Level = true,
                            Subject = "Polski",
                            Title = "Ponad słowami 2 cz. 1"
                        },
                        new
                        {
                            Id = 4,
                            Level = true,
                            Subject = "Polski",
                            Title = "Ponad słowami 2 cz. 2"
                        },
                        new
                        {
                            Id = 5,
                            Level = true,
                            Subject = "Polski",
                            Title = "Ponad słowami 3 cz. 1"
                        },
                        new
                        {
                            Id = 6,
                            Level = true,
                            Subject = "Polski",
                            Title = "Ponad słowami 3 cz. 2"
                        },
                        new
                        {
                            Id = 7,
                            Level = true,
                            Subject = "Polski",
                            Title = "Ponad słowami 4"
                        },
                        new
                        {
                            Id = 8,
                            Level = true,
                            Subject = "Język angielski",
                            Title = "Focus 2 Podręcznik"
                        },
                        new
                        {
                            Id = 9,
                            Level = true,
                            Subject = "Język angielski",
                            Title = "Focus 3 Podręcznik"
                        },
                        new
                        {
                            Id = 10,
                            Level = true,
                            Subject = "Język angielski",
                            Title = "Focus 4 Podręcznik"
                        },
                        new
                        {
                            Id = 11,
                            Level = true,
                            Subject = "Język angielski",
                            Title = "Focus 5 Podręcznik"
                        },
                        new
                        {
                            Id = 12,
                            Level = true,
                            Subject = "Język angielski",
                            Title = "Focus 2 Ćwiczenia"
                        },
                        new
                        {
                            Id = 13,
                            Level = true,
                            Subject = "Język angielski",
                            Title = "Focus 3 Ćwiczenia"
                        },
                        new
                        {
                            Id = 14,
                            Level = true,
                            Subject = "Język angielski",
                            Title = "Focus 4 Ćwiczenia"
                        },
                        new
                        {
                            Id = 15,
                            Level = true,
                            Subject = "Język angielski",
                            Title = "Focus 5 Ćwiczenia"
                        },
                        new
                        {
                            Id = 16,
                            Level = true,
                            Subject = "Język angielski",
                            Title = "My matura perspectives [nowa era]"
                        },
                        new
                        {
                            Id = 17,
                            Level = true,
                            Subject = "Język angielski",
                            Title = "Repetytorium [Macmillan]"
                        },
                        new
                        {
                            Id = 18,
                            Level = false,
                            Subject = "Język angielski",
                            Title = "Repetytorium maturzysty [Oxford]"
                        },
                        new
                        {
                            Id = 19,
                            Level = true,
                            Subject = "Język angielski",
                            Title = "Repetytorium maturzysty [Cambridge, PWN]"
                        },
                        new
                        {
                            Id = 20,
                            Level = true,
                            Subject = "Język Niemiecki",
                            Title = "Welttour Deutsch 1"
                        },
                        new
                        {
                            Id = 21,
                            Level = true,
                            Subject = "Język Niemiecki",
                            Title = "Welttour Deutsch 2"
                        },
                        new
                        {
                            Id = 22,
                            Level = true,
                            Subject = "Język Niemiecki",
                            Title = "Welttour Deutsch 3"
                        },
                        new
                        {
                            Id = 23,
                            Level = true,
                            Subject = "Język Niemiecki",
                            Title = "Welttour Deutsch 4"
                        },
                        new
                        {
                            Id = 24,
                            Level = true,
                            Subject = "Język Niemiecki",
                            Title = "Effekt 1"
                        },
                        new
                        {
                            Id = 25,
                            Level = true,
                            Subject = "Język Niemiecki",
                            Title = "Effekt 2"
                        },
                        new
                        {
                            Id = 26,
                            Level = true,
                            Subject = "Język Niemiecki",
                            Title = "Effekt 3"
                        },
                        new
                        {
                            Id = 27,
                            Level = true,
                            Subject = "Język Niemiecki",
                            Title = "Effekt 4"
                        },
                        new
                        {
                            Id = 28,
                            Level = true,
                            Subject = "Biologia",
                            Title = "Biologia na czasie 1"
                        },
                        new
                        {
                            Id = 29,
                            Level = true,
                            Subject = "Biologia",
                            Title = "Biologia na czasie 2"
                        },
                        new
                        {
                            Id = 30,
                            Level = true,
                            Subject = "Biologia",
                            Title = "Biologia na czasie 3"
                        },
                        new
                        {
                            Id = 31,
                            Level = false,
                            Subject = "Biologia",
                            Title = "Biologia na czasie 1"
                        },
                        new
                        {
                            Id = 32,
                            Level = false,
                            Subject = "Biologia",
                            Title = "Biologia na czasie 2"
                        },
                        new
                        {
                            Id = 33,
                            Level = false,
                            Subject = "Biologia",
                            Title = "Biologia na czasie 3"
                        },
                        new
                        {
                            Id = 34,
                            Level = true,
                            Subject = "Chemia",
                            Title = "To jest chemia 1"
                        },
                        new
                        {
                            Id = 35,
                            Level = true,
                            Subject = "Chemia",
                            Title = "To jest chemia 2"
                        },
                        new
                        {
                            Id = 36,
                            Level = false,
                            Subject = "Chemia",
                            Title = "To jest chemia 1"
                        },
                        new
                        {
                            Id = 37,
                            Level = false,
                            Subject = "Chemia",
                            Title = "To jest chemia 2"
                        },
                        new
                        {
                            Id = 38,
                            Level = true,
                            Subject = "EDB",
                            Title = "Edukacja dla bezpieczeństwa [wsip]"
                        },
                        new
                        {
                            Id = 39,
                            Level = false,
                            Subject = "Fizyka",
                            Title = "Fizyka 1 [wsip]"
                        },
                        new
                        {
                            Id = 40,
                            Level = false,
                            Subject = "Fizyka",
                            Title = "Fizyka 2 [wsip]"
                        },
                        new
                        {
                            Id = 41,
                            Level = false,
                            Subject = "Fizyka",
                            Title = "Fizyka 3 [wsip]"
                        },
                        new
                        {
                            Id = 42,
                            Level = false,
                            Subject = "Fizyka",
                            Title = "Fizyka 4 [wsip]"
                        },
                        new
                        {
                            Id = 43,
                            Level = true,
                            Subject = "Fizyka",
                            Title = "Fizyka 1 [wsip]"
                        },
                        new
                        {
                            Id = 44,
                            Level = true,
                            Subject = "Fizyka",
                            Title = "Fizyka 2 [wsip]"
                        },
                        new
                        {
                            Id = 45,
                            Level = true,
                            Subject = "Fizyka",
                            Title = "Fizyka 3 [wsip]"
                        },
                        new
                        {
                            Id = 46,
                            Level = true,
                            Subject = "Fizyka",
                            Title = "Fizyka 4 [wsip]"
                        },
                        new
                        {
                            Id = 47,
                            Level = true,
                            Subject = "Geografia",
                            Title = "Oblicza geografii 1"
                        },
                        new
                        {
                            Id = 48,
                            Level = true,
                            Subject = "Geografia",
                            Title = "Oblicza geografii 2"
                        },
                        new
                        {
                            Id = 49,
                            Level = true,
                            Subject = "Geografia",
                            Title = "Oblicz geografii karty pracy 1"
                        },
                        new
                        {
                            Id = 50,
                            Level = true,
                            Subject = "Geografia",
                            Title = "Oblicz geografii karty pracy 2"
                        },
                        new
                        {
                            Id = 51,
                            Level = true,
                            Subject = "Historia",
                            Title = "Historia [wsip] 1"
                        },
                        new
                        {
                            Id = 52,
                            Level = true,
                            Subject = "Historia",
                            Title = "Historia [wsip] 2"
                        },
                        new
                        {
                            Id = 53,
                            Level = true,
                            Subject = "Historia",
                            Title = "Historia [wsip] 3"
                        },
                        new
                        {
                            Id = 54,
                            Level = true,
                            Subject = "Historia",
                            Title = "Historia [wsip] 4"
                        },
                        new
                        {
                            Id = 55,
                            Level = true,
                            Subject = "HiT",
                            Title = "Historia i teraźniejszość [wsip] 1"
                        },
                        new
                        {
                            Id = 56,
                            Level = true,
                            Subject = "HiT",
                            Title = "Historia i teraźniejszość [wsip] 2"
                        },
                        new
                        {
                            Id = 57,
                            Level = true,
                            Subject = "Informatyka",
                            Title = "Informatyka [operon]"
                        },
                        new
                        {
                            Id = 58,
                            Level = true,
                            Subject = "Informatyka",
                            Title = "Informatyka dla szkół ponadgimnazjalnych [Migra]"
                        },
                        new
                        {
                            Id = 59,
                            Level = false,
                            Subject = "Informatyka",
                            Title = "Informatyka [operon]"
                        },
                        new
                        {
                            Id = 60,
                            Level = false,
                            Subject = "Informatyka",
                            Title = "Informatyka dla szkół ponadgimnazjalnych [Migra]"
                        },
                        new
                        {
                            Id = 61,
                            Level = true,
                            Subject = "Matematyka",
                            Title = "NOWA MATeMAtyka 1"
                        },
                        new
                        {
                            Id = 62,
                            Level = true,
                            Subject = "Matematyka",
                            Title = "NOWA MATeMAtyka 2"
                        },
                        new
                        {
                            Id = 63,
                            Level = true,
                            Subject = "Matematyka",
                            Title = "NOWA MATeMAtyka 3"
                        },
                        new
                        {
                            Id = 64,
                            Level = true,
                            Subject = "Matematyka",
                            Title = "NOWA MATeMAtyka 4"
                        },
                        new
                        {
                            Id = 65,
                            Level = false,
                            Subject = "Matematyka",
                            Title = "NOWA MATeMAtyka 1"
                        },
                        new
                        {
                            Id = 66,
                            Level = false,
                            Subject = "Matematyka",
                            Title = "NOWA MATeMAtyka 2"
                        },
                        new
                        {
                            Id = 67,
                            Level = false,
                            Subject = "Matematyka",
                            Title = "NOWA MATeMAtyka 3"
                        },
                        new
                        {
                            Id = 68,
                            Level = false,
                            Subject = "Matematyka",
                            Title = "NOWA MATeMAtyka 4"
                        },
                        new
                        {
                            Id = 69,
                            Level = true,
                            Subject = "Podstawy przedsiębiorczości",
                            Title = "Krok w przedsiębiorczość"
                        },
                        new
                        {
                            Id = 70,
                            Level = true,
                            Subject = "Biznes i zarządzanie",
                            Title = "Krok w biznes i zarządzanie 1"
                        },
                        new
                        {
                            Id = 71,
                            Level = true,
                            Subject = "Biznes i zarządzanie",
                            Title = "Krok w biznes i zarządzanie 2"
                        },
                        new
                        {
                            Id = 72,
                            Level = true,
                            Subject = "Plastyka",
                            Title = "Spotkania ze sztuką 1"
                        },
                        new
                        {
                            Id = 73,
                            Level = true,
                            Subject = "WOS",
                            Title = "W centrum uwagi 1"
                        },
                        new
                        {
                            Id = 74,
                            Level = true,
                            Subject = "WOS",
                            Title = "W centrum uwagi 2"
                        },
                        new
                        {
                            Id = 75,
                            Level = false,
                            Subject = "Angielski zawodowy",
                            Title = "Electronics"
                        },
                        new
                        {
                            Id = 76,
                            Level = false,
                            Subject = "Angielski zawodowy",
                            Title = "Electrician"
                        },
                        new
                        {
                            Id = 77,
                            Level = false,
                            Subject = "Angielski zawodowy",
                            Title = "Software engineering"
                        },
                        new
                        {
                            Id = 78,
                            Level = true,
                            Subject = "Angielski zawodowy",
                            Title = "IT [english for IT]"
                        },
                        new
                        {
                            Id = 79,
                            Level = false,
                            Subject = "Informatyka",
                            Title = "Informatyka w praktyce"
                        });
                });

            modelBuilder.Entity("Booker.Data.BookGrade", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("GradeId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("BookId", "GradeId");

                    b.HasIndex("GradeId");

                    b.ToTable("BookGrades");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            GradeId = "1"
                        },
                        new
                        {
                            BookId = 2,
                            GradeId = "1"
                        },
                        new
                        {
                            BookId = 3,
                            GradeId = "2"
                        },
                        new
                        {
                            BookId = 4,
                            GradeId = "2"
                        },
                        new
                        {
                            BookId = 5,
                            GradeId = "3"
                        },
                        new
                        {
                            BookId = 6,
                            GradeId = "4"
                        },
                        new
                        {
                            BookId = 7,
                            GradeId = "5"
                        },
                        new
                        {
                            BookId = 8,
                            GradeId = "1"
                        },
                        new
                        {
                            BookId = 9,
                            GradeId = "1"
                        },
                        new
                        {
                            BookId = 10,
                            GradeId = "2"
                        },
                        new
                        {
                            BookId = 11,
                            GradeId = "2"
                        },
                        new
                        {
                            BookId = 12,
                            GradeId = "3"
                        },
                        new
                        {
                            BookId = 13,
                            GradeId = "3"
                        },
                        new
                        {
                            BookId = 14,
                            GradeId = "4"
                        },
                        new
                        {
                            BookId = 15,
                            GradeId = "4"
                        },
                        new
                        {
                            BookId = 16,
                            GradeId = "5"
                        },
                        new
                        {
                            BookId = 17,
                            GradeId = "5"
                        },
                        new
                        {
                            BookId = 18,
                            GradeId = "5"
                        },
                        new
                        {
                            BookId = 19,
                            GradeId = "5"
                        },
                        new
                        {
                            BookId = 20,
                            GradeId = "1"
                        },
                        new
                        {
                            BookId = 21,
                            GradeId = "2"
                        },
                        new
                        {
                            BookId = 22,
                            GradeId = "3"
                        },
                        new
                        {
                            BookId = 23,
                            GradeId = "4"
                        },
                        new
                        {
                            BookId = 24,
                            GradeId = "1"
                        },
                        new
                        {
                            BookId = 25,
                            GradeId = "2"
                        },
                        new
                        {
                            BookId = 26,
                            GradeId = "3"
                        },
                        new
                        {
                            BookId = 27,
                            GradeId = "4"
                        },
                        new
                        {
                            BookId = 28,
                            GradeId = "1"
                        },
                        new
                        {
                            BookId = 29,
                            GradeId = "2"
                        },
                        new
                        {
                            BookId = 30,
                            GradeId = "3"
                        },
                        new
                        {
                            BookId = 31,
                            GradeId = "1"
                        },
                        new
                        {
                            BookId = 32,
                            GradeId = "2"
                        },
                        new
                        {
                            BookId = 33,
                            GradeId = "3"
                        },
                        new
                        {
                            BookId = 34,
                            GradeId = "1"
                        },
                        new
                        {
                            BookId = 35,
                            GradeId = "2"
                        },
                        new
                        {
                            BookId = 36,
                            GradeId = "3"
                        },
                        new
                        {
                            BookId = 37,
                            GradeId = "4"
                        },
                        new
                        {
                            BookId = 38,
                            GradeId = "1"
                        },
                        new
                        {
                            BookId = 39,
                            GradeId = "1"
                        },
                        new
                        {
                            BookId = 40,
                            GradeId = "2"
                        },
                        new
                        {
                            BookId = 41,
                            GradeId = "3"
                        },
                        new
                        {
                            BookId = 42,
                            GradeId = "4"
                        },
                        new
                        {
                            BookId = 43,
                            GradeId = "1"
                        },
                        new
                        {
                            BookId = 44,
                            GradeId = "2"
                        },
                        new
                        {
                            BookId = 45,
                            GradeId = "3"
                        },
                        new
                        {
                            BookId = 46,
                            GradeId = "4"
                        },
                        new
                        {
                            BookId = 47,
                            GradeId = "1"
                        },
                        new
                        {
                            BookId = 48,
                            GradeId = "2"
                        },
                        new
                        {
                            BookId = 49,
                            GradeId = "1"
                        },
                        new
                        {
                            BookId = 50,
                            GradeId = "2"
                        },
                        new
                        {
                            BookId = 51,
                            GradeId = "1"
                        },
                        new
                        {
                            BookId = 52,
                            GradeId = "2"
                        },
                        new
                        {
                            BookId = 53,
                            GradeId = "3"
                        },
                        new
                        {
                            BookId = 54,
                            GradeId = "4"
                        },
                        new
                        {
                            BookId = 55,
                            GradeId = "2"
                        },
                        new
                        {
                            BookId = 56,
                            GradeId = "3"
                        },
                        new
                        {
                            BookId = 57,
                            GradeId = "1"
                        },
                        new
                        {
                            BookId = 58,
                            GradeId = "2"
                        },
                        new
                        {
                            BookId = 59,
                            GradeId = "3"
                        },
                        new
                        {
                            BookId = 60,
                            GradeId = "4"
                        },
                        new
                        {
                            BookId = 61,
                            GradeId = "1"
                        },
                        new
                        {
                            BookId = 62,
                            GradeId = "2"
                        },
                        new
                        {
                            BookId = 63,
                            GradeId = "3"
                        },
                        new
                        {
                            BookId = 64,
                            GradeId = "4"
                        },
                        new
                        {
                            BookId = 65,
                            GradeId = "1"
                        },
                        new
                        {
                            BookId = 66,
                            GradeId = "2"
                        },
                        new
                        {
                            BookId = 67,
                            GradeId = "3"
                        },
                        new
                        {
                            BookId = 68,
                            GradeId = "4"
                        },
                        new
                        {
                            BookId = 69,
                            GradeId = "2"
                        },
                        new
                        {
                            BookId = 70,
                            GradeId = "1"
                        },
                        new
                        {
                            BookId = 71,
                            GradeId = "2"
                        },
                        new
                        {
                            BookId = 72,
                            GradeId = "1"
                        },
                        new
                        {
                            BookId = 73,
                            GradeId = "4"
                        },
                        new
                        {
                            BookId = 74,
                            GradeId = "5"
                        },
                        new
                        {
                            BookId = 75,
                            GradeId = "3"
                        },
                        new
                        {
                            BookId = 76,
                            GradeId = "3"
                        },
                        new
                        {
                            BookId = 77,
                            GradeId = "3"
                        },
                        new
                        {
                            BookId = 78,
                            GradeId = "3"
                        });
                });

            modelBuilder.Entity("Booker.Data.Grade", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GradeNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Grades");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            GradeNumber = "1"
                        },
                        new
                        {
                            Id = "2",
                            GradeNumber = "2"
                        },
                        new
                        {
                            Id = "3",
                            GradeNumber = "3"
                        },
                        new
                        {
                            Id = "4",
                            GradeNumber = "4"
                        },
                        new
                        {
                            Id = "5",
                            GradeNumber = "5"
                        });
                });

            modelBuilder.Entity("Booker.Data.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserID");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 73,
                            DateTime = new DateTime(2025, 1, 11, 19, 43, 18, 355, DateTimeKind.Local).AddTicks(9369),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 43m,
                            State = "bardzo dobry",
                            UserID = 1
                        },
                        new
                        {
                            Id = 2,
                            BookId = 3,
                            DateTime = new DateTime(2025, 1, 11, 19, 43, 18, 355, DateTimeKind.Local).AddTicks(9412),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 52.428571428571428571428571429m,
                            State = "bardzo dobry",
                            UserID = 2
                        },
                        new
                        {
                            Id = 3,
                            BookId = 40,
                            DateTime = new DateTime(2025, 1, 11, 19, 43, 18, 355, DateTimeKind.Local).AddTicks(9416),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 56.857142857142857142857142857m,
                            State = "bardzo dobry",
                            UserID = 3
                        },
                        new
                        {
                            Id = 4,
                            BookId = 21,
                            DateTime = new DateTime(2025, 1, 11, 19, 43, 18, 355, DateTimeKind.Local).AddTicks(9419),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 35m,
                            State = "bardzo dobry",
                            UserID = 4
                        },
                        new
                        {
                            Id = 5,
                            BookId = 56,
                            DateTime = new DateTime(2025, 1, 11, 19, 43, 18, 355, DateTimeKind.Local).AddTicks(9422),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 67.285714285714285714285714286m,
                            State = "bardzo dobry",
                            UserID = 5
                        },
                        new
                        {
                            Id = 6,
                            BookId = 61,
                            DateTime = new DateTime(2025, 1, 11, 19, 43, 18, 355, DateTimeKind.Local).AddTicks(9425),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 31m,
                            State = "bardzo dobry",
                            UserID = 1
                        },
                        new
                        {
                            Id = 7,
                            BookId = 35,
                            DateTime = new DateTime(2025, 1, 11, 19, 43, 18, 355, DateTimeKind.Local).AddTicks(9428),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 38.714285714285714285714285714m,
                            State = "bardzo dobry",
                            UserID = 2
                        },
                        new
                        {
                            Id = 8,
                            BookId = 72,
                            DateTime = new DateTime(2025, 1, 11, 19, 43, 18, 355, DateTimeKind.Local).AddTicks(9432),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 63.714285714285714285714285714m,
                            State = "bardzo dobry",
                            UserID = 3
                        },
                        new
                        {
                            Id = 9,
                            BookId = 43,
                            DateTime = new DateTime(2025, 1, 11, 19, 43, 18, 355, DateTimeKind.Local).AddTicks(9434),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 62.714285714285714285714285714m,
                            State = "bardzo dobry",
                            UserID = 4
                        },
                        new
                        {
                            Id = 10,
                            BookId = 56,
                            DateTime = new DateTime(2025, 1, 11, 19, 43, 18, 355, DateTimeKind.Local).AddTicks(9437),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 56.714285714285714285714285714m,
                            State = "bardzo dobry",
                            UserID = 5
                        },
                        new
                        {
                            Id = 11,
                            BookId = 21,
                            DateTime = new DateTime(2025, 1, 11, 19, 43, 18, 355, DateTimeKind.Local).AddTicks(9440),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 20.571428571428571428571428571m,
                            State = "bardzo dobry",
                            UserID = 1
                        },
                        new
                        {
                            Id = 12,
                            BookId = 10,
                            DateTime = new DateTime(2025, 1, 11, 19, 43, 18, 355, DateTimeKind.Local).AddTicks(9442),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 49.714285714285714285714285714m,
                            State = "bardzo dobry",
                            UserID = 2
                        },
                        new
                        {
                            Id = 13,
                            BookId = 23,
                            DateTime = new DateTime(2025, 1, 11, 19, 43, 18, 355, DateTimeKind.Local).AddTicks(9445),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 45.142857142857142857142857143m,
                            State = "bardzo dobry",
                            UserID = 3
                        },
                        new
                        {
                            Id = 14,
                            BookId = 9,
                            DateTime = new DateTime(2025, 1, 11, 19, 43, 18, 355, DateTimeKind.Local).AddTicks(9448),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 32.285714285714285714285714286m,
                            State = "bardzo dobry",
                            UserID = 4
                        },
                        new
                        {
                            Id = 15,
                            BookId = 34,
                            DateTime = new DateTime(2025, 1, 11, 19, 43, 18, 355, DateTimeKind.Local).AddTicks(9451),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 74.285714285714285714285714286m,
                            State = "bardzo dobry",
                            UserID = 5
                        },
                        new
                        {
                            Id = 16,
                            BookId = 2,
                            DateTime = new DateTime(2025, 1, 11, 19, 43, 18, 355, DateTimeKind.Local).AddTicks(9455),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 81.57142857142857142857142857m,
                            State = "bardzo dobry",
                            UserID = 1
                        },
                        new
                        {
                            Id = 17,
                            BookId = 44,
                            DateTime = new DateTime(2025, 1, 11, 19, 43, 18, 355, DateTimeKind.Local).AddTicks(9458),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 46.285714285714285714285714286m,
                            State = "bardzo dobry",
                            UserID = 2
                        },
                        new
                        {
                            Id = 18,
                            BookId = 44,
                            DateTime = new DateTime(2025, 1, 11, 19, 43, 18, 355, DateTimeKind.Local).AddTicks(9461),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 68.285714285714285714285714286m,
                            State = "bardzo dobry",
                            UserID = 3
                        },
                        new
                        {
                            Id = 19,
                            BookId = 70,
                            DateTime = new DateTime(2025, 1, 11, 19, 43, 18, 355, DateTimeKind.Local).AddTicks(9463),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 61.142857142857142857142857143m,
                            State = "bardzo dobry",
                            UserID = 4
                        },
                        new
                        {
                            Id = 20,
                            BookId = 56,
                            DateTime = new DateTime(2025, 1, 11, 19, 43, 18, 355, DateTimeKind.Local).AddTicks(9466),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 36.857142857142857142857142857m,
                            State = "bardzo dobry",
                            UserID = 5
                        },
                        new
                        {
                            Id = 21,
                            BookId = 74,
                            DateTime = new DateTime(2025, 1, 11, 19, 43, 18, 355, DateTimeKind.Local).AddTicks(9469),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 75.428571428571428571428571429m,
                            State = "bardzo dobry",
                            UserID = 1
                        },
                        new
                        {
                            Id = 22,
                            BookId = 26,
                            DateTime = new DateTime(2025, 1, 11, 19, 43, 18, 355, DateTimeKind.Local).AddTicks(9471),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 61.285714285714285714285714286m,
                            State = "bardzo dobry",
                            UserID = 2
                        },
                        new
                        {
                            Id = 23,
                            BookId = 41,
                            DateTime = new DateTime(2025, 1, 11, 19, 43, 18, 355, DateTimeKind.Local).AddTicks(9475),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 73m,
                            State = "bardzo dobry",
                            UserID = 3
                        },
                        new
                        {
                            Id = 24,
                            BookId = 26,
                            DateTime = new DateTime(2025, 1, 11, 19, 43, 18, 355, DateTimeKind.Local).AddTicks(9477),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 69.571428571428571428571428571m,
                            State = "bardzo dobry",
                            UserID = 4
                        },
                        new
                        {
                            Id = 25,
                            BookId = 56,
                            DateTime = new DateTime(2025, 1, 11, 19, 43, 18, 355, DateTimeKind.Local).AddTicks(9480),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 83.14285714285714285714285714m,
                            State = "bardzo dobry",
                            UserID = 5
                        },
                        new
                        {
                            Id = 26,
                            BookId = 55,
                            DateTime = new DateTime(2025, 1, 11, 19, 43, 18, 355, DateTimeKind.Local).AddTicks(9483),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 53.714285714285714285714285714m,
                            State = "bardzo dobry",
                            UserID = 1
                        },
                        new
                        {
                            Id = 27,
                            BookId = 51,
                            DateTime = new DateTime(2025, 1, 11, 19, 43, 18, 355, DateTimeKind.Local).AddTicks(9510),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 74.285714285714285714285714286m,
                            State = "bardzo dobry",
                            UserID = 2
                        },
                        new
                        {
                            Id = 28,
                            BookId = 62,
                            DateTime = new DateTime(2025, 1, 11, 19, 43, 18, 355, DateTimeKind.Local).AddTicks(9555),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 25.142857142857142857142857143m,
                            State = "bardzo dobry",
                            UserID = 3
                        },
                        new
                        {
                            Id = 29,
                            BookId = 19,
                            DateTime = new DateTime(2025, 1, 11, 19, 43, 18, 355, DateTimeKind.Local).AddTicks(9558),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 20.428571428571428571428571429m,
                            State = "bardzo dobry",
                            UserID = 4
                        },
                        new
                        {
                            Id = 30,
                            BookId = 25,
                            DateTime = new DateTime(2025, 1, 11, 19, 43, 18, 355, DateTimeKind.Local).AddTicks(9561),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 22m,
                            State = "bardzo dobry",
                            UserID = 5
                        },
                        new
                        {
                            Id = 31,
                            BookId = 71,
                            DateTime = new DateTime(2025, 1, 11, 19, 43, 18, 355, DateTimeKind.Local).AddTicks(9564),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 69.571428571428571428571428571m,
                            State = "bardzo dobry",
                            UserID = 1
                        },
                        new
                        {
                            Id = 32,
                            BookId = 38,
                            DateTime = new DateTime(2025, 1, 11, 19, 43, 18, 355, DateTimeKind.Local).AddTicks(9567),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 23.714285714285714285714285714m,
                            State = "bardzo dobry",
                            UserID = 2
                        },
                        new
                        {
                            Id = 33,
                            BookId = 40,
                            DateTime = new DateTime(2025, 1, 11, 19, 43, 18, 355, DateTimeKind.Local).AddTicks(9570),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 58.428571428571428571428571429m,
                            State = "bardzo dobry",
                            UserID = 3
                        },
                        new
                        {
                            Id = 34,
                            BookId = 46,
                            DateTime = new DateTime(2025, 1, 11, 19, 43, 18, 355, DateTimeKind.Local).AddTicks(9572),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 32.714285714285714285714285714m,
                            State = "bardzo dobry",
                            UserID = 4
                        },
                        new
                        {
                            Id = 35,
                            BookId = 1,
                            DateTime = new DateTime(2025, 1, 11, 19, 43, 18, 355, DateTimeKind.Local).AddTicks(9575),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 22.285714285714285714285714286m,
                            State = "bardzo dobry",
                            UserID = 5
                        },
                        new
                        {
                            Id = 36,
                            BookId = 45,
                            DateTime = new DateTime(2025, 1, 11, 19, 43, 18, 355, DateTimeKind.Local).AddTicks(9578),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 38.714285714285714285714285714m,
                            State = "bardzo dobry",
                            UserID = 1
                        },
                        new
                        {
                            Id = 37,
                            BookId = 16,
                            DateTime = new DateTime(2025, 1, 11, 19, 43, 18, 355, DateTimeKind.Local).AddTicks(9580),
                            Description = "Książka w dobrym stanie, prawie nie używana, nie zalana, rogi delikatnie zagięte, polecam kebab Zahir i pytam czy idziecie na sylwestra do zduniaka.",
                            Photo = "https://images.unsplash.com/photo-1517770413964-df8ca61194a6?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Price = 68.857142857142857142857142857m,
                            State = "bardzo dobry",
                            UserID = 2
                        });
                });

            modelBuilder.Entity("Booker.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("School")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "user1@gmail.com",
                            Nickname = "user1",
                            Password = "zaq1@WSX",
                            Photo = "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png",
                            School = "Śl.TZN"
                        },
                        new
                        {
                            Id = 2,
                            Email = "user2@gmail.com",
                            Nickname = "user2",
                            Password = "zaq1@WSX",
                            Photo = "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png",
                            School = "Śl.TZN"
                        },
                        new
                        {
                            Id = 3,
                            Email = "user3@gmail.com",
                            Nickname = "user3",
                            Password = "zaq1@WSX",
                            Photo = "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png",
                            School = "Śl.TZN"
                        },
                        new
                        {
                            Id = 4,
                            Email = "user4@gmail.com",
                            Nickname = "user4",
                            Password = "zaq1@WSX",
                            Photo = "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png",
                            School = "Śl.TZN"
                        },
                        new
                        {
                            Id = 5,
                            Email = "user5@gmail.com",
                            Nickname = "user5",
                            Password = "zaq1@WSX",
                            Photo = "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png",
                            School = "Śl.TZN"
                        });
                });

            modelBuilder.Entity("Booker.Data.BookGrade", b =>
                {
                    b.HasOne("Booker.Data.Book", "Book")
                        .WithMany("BookGrades")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Booker.Data.Grade", "Grade")
                        .WithMany("BookGrades")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Grade");
                });

            modelBuilder.Entity("Booker.Data.Item", b =>
                {
                    b.HasOne("Booker.Data.Book", "Book")
                        .WithMany("Items")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Booker.Data.User", "User")
                        .WithMany("Items")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Booker.Data.Book", b =>
                {
                    b.Navigation("BookGrades");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("Booker.Data.Grade", b =>
                {
                    b.Navigation("BookGrades");
                });

            modelBuilder.Entity("Booker.Data.User", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
